version: '3.4'

services:

  curator:
    container_name: curator
    build:
      context: extensions/curator/
      args:
       CURATOR_VERSION: 5.5.4
       CRON: "0 5 * * *"
    environment:
      TZ: $TIMEZONE
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped
