version: '3.4'

services:

  curator:
    container_name: curator
    build:
      context: extensions/curator/
      args:
       CURATOR_VERSION: 5.5.4
       CRON: "0 5 * * *"
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      UNIT_COUNT: 90
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped
    environment:
      - TZ=$TIMEZONE
